/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-06-04 12:18:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>LOGIN PAGE</title>\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"./assets/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"./assets/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin css for this page -->\r\n");
      out.write("<!-- End plugin css for this page -->\r\n");
      out.write("<!-- inject:css -->\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./assets/css/style.css\">\r\n");
      out.write("<!-- End layout styles -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./assets/images/favicon.ico\" />\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".auth .auth-form-light {\r\n");
      out.write("	background: #ffffff;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth form .auth-form-btn {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	line-height: 1.5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-gradient-primary {\r\n");
      out.write("	background: -webkit-gradient(linear, left top, right top, from(#da8cff),\r\n");
      out.write("		to(#9a55ff));\r\n");
      out.write("	background: linear-gradient(to right, #6073e3, #6073e3);\r\n");
      out.write("	border: 0;\r\n");
      out.write("	-webkit-transition: opacity 0.3s ease;\r\n");
      out.write("	transition: opacity 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("p.error {\r\n");
      out.write("    color: red;\r\n");
      out.write("    border: 2px solid dotted;\r\n");
      out.write("    border: dotted;\r\n");
      out.write("    width: 215px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth .brand-logo {\r\n");
      out.write("	margin-bottom: 2rem;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-scroller\">\r\n");
      out.write("		<div class=\"container-fluid page-body-wrapper full-page-wrapper\">\r\n");
      out.write("			<div class=\"content-wrapper d-flex align-items-center auth\">\r\n");
      out.write("				<div class=\"row flex-grow\">\r\n");
      out.write("					<div class=\"col-lg-4 mx-auto\">\r\n");
      out.write("						<div class=\"auth-form-light text-left p-5\">\r\n");
      out.write("							<div class=\"brand-logo\">\r\n");
      out.write("								<img src=\"./assets/images/logo2.png\"\r\n");
      out.write("									style=\"width: 50%; height: 50%;\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<form class=\"pt-3\" action=\"./PhoneBookController\" method=\"post\">\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<input type=\"email\" class=\"form-control form-control-lg\"\r\n");
      out.write("										id=\"exampleInputEmail1\" name=\"Email\"\r\n");
      out.write("										placeholder=\"Enter Email Id\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<input type=\"password\" class=\"form-control form-control-lg\"\r\n");
      out.write("										id=\"exampleInputPassword1\" name=\"Password\"\r\n");
      out.write("										placeholder=\"Enter Password\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"mt-3\">\r\n");
      out.write("									<input type=\"hidden\" value=\"LOGIN\" Class=\"formController\"\r\n");
      out.write("										name=\"Action\">\r\n");
      out.write("									<button\r\n");
      out.write("										class=\"btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn\"\r\n");
      out.write("										href=\"./PhoneBookController\">SIGN IN</button>\r\n");
      out.write("										");
if(request.getAttribute("msg")!=null) {
      out.write("\r\n");
      out.write("										\r\n");
      out.write("									 	<p class=\"error\">");
      out.print(request.getAttribute("msg") );
      out.write("</p> \r\n");
      out.write("										");
} 
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"my-2 d-flex justify-content-center align-items-center\">\r\n");
      out.write("									<!-- <div class=\"form-check\">\r\n");
      out.write("                      <label class=\"form-check-label text-muted\">\r\n");
      out.write("                        <input type=\"checkbox\" class=\"form-check-input\"> Keep me signed in </label>\r\n");
      out.write("                    </div> -->     \r\n");
      out.write("                        \r\n");
      out.write("                                \r\n");
      out.write("									<a href=\"Usersignup.jsp \" >Create new Account</a><a\r\n");
      out.write("										href=\"forget.html\" class=\"auth-link\"\r\n");
      out.write("										style=\"color: #6073e3; margin-top: 3rem; font-weight: 200; font-size: 1rem; text-align: center;\">Forgot\r\n");
      out.write("										password?</a>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- content-wrapper ends -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- page-body-wrapper ends -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- container-scroller -->\r\n");
      out.write("	<!-- plugins:js -->\r\n");
      out.write("	<script src=\"../../assets/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("	<!-- endinject -->\r\n");
      out.write("	<!-- Plugin js for this page -->\r\n");
      out.write("	<!-- End plugin js for this page -->\r\n");
      out.write("	<!-- inject:js -->\r\n");
      out.write("	<script src=\"../../assets/js/off-canvas.js\"></script>\r\n");
      out.write("	<script src=\"../../assets/js/hoverable-collapse.js\"></script>\r\n");
      out.write("	<script src=\"../../assets/js/misc.js\"></script>\r\n");
      out.write("	<!-- endinject -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
