/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-05-29 16:17:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.adda.app.Bean.User;
import com.adda.app.Bean.Group;
import java.util.ArrayList;

public final class UserDesboard1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.adda.app.Bean.Group");
    _jspx_imports_classes.add("com.adda.app.Bean.User");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>Admin</title>\r\n");
      out.write("    <!-- plugins:css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- endinject -->\r\n");
      out.write("    <!-- Plugin css for this page -->\r\n");
      out.write("    <!-- End plugin css for this page -->\r\n");
      out.write("    <!-- inject:css -->\r\n");
      out.write("    <!-- endinject -->\r\n");
      out.write("    <!-- Layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("    <!-- End layout styles -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/images/favicon.ico\" />\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/yourcode.js\" crossorigin=\"anonymous\"></script>                                     \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("      <!-- modal -->\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto|Varela+Round\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("      <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("      <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\r\n");
      out.write("      <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <style>\r\n");
      out.write("    .modal-content {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: -ms-flexbox;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    -ms-flex-direction: column;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    pointer-events: auto;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    background-clip: padding-box;\r\n");
      out.write("    border: 1px solid rgba(0,0,0,.2);\r\n");
      out.write("    border-radius: 0.3rem;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    margin-top: 7rem;\r\n");
      out.write("}\r\n");
      out.write("p.error {\r\n");
      out.write("    color: red;\r\n");
      out.write("    font-style: cursive;\r\n");
      out.write("}\r\n");
      out.write("    .card-text{\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("    .mdi-24px.mdi:before {\r\n");
      out.write("    font-size: 35px;\r\n");
      out.write("}\r\n");
      out.write("  /* password change */\r\n");
      out.write("  .mainDiv {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("    font-family: 'Open Sans', sans-serif;\r\n");
      out.write("  }\r\n");
      out.write(" .cardStyle {\r\n");
      out.write("  width: 381px;\r\n");
      out.write("    border-color: white;\r\n");
      out.write("    /* background: #fff; */\r\n");
      out.write("    /* padding: 36px 0; */\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    margin: 30px 0;\r\n");
      out.write("    box-shadow: 0px 0 2px 0 rgba(0,0,0,0.25);\r\n");
      out.write("  }\r\n");
      out.write("#signupLogo {\r\n");
      out.write("  max-height: 100px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write(".formTitle{\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  color: #2F2D3B;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".inputLabel {\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  color: #555;\r\n");
      out.write("  margin-bottom: 6px;\r\n");
      out.write("  margin-top: 24px;\r\n");
      out.write("}\r\n");
      out.write("  .inputDiv {\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("  }\r\n");
      out.write("input {\r\n");
      out.write("  height: 40px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border: solid 1px #ccc;\r\n");
      out.write("  padding: 0 11px;\r\n");
      out.write("}\r\n");
      out.write("input:disabled {\r\n");
      out.write("  cursor: not-allowed;\r\n");
      out.write("  border: solid 1px #eee;\r\n");
      out.write("}\r\n");
      out.write(".buttonWrapper {\r\n");
      out.write("  margin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("  .submitButton {\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #065492;\r\n");
      out.write("    border-color: #065492;\r\n");
      out.write("    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("    box-shadow: 0 2px 0 rgba(0, 0, 0, 0.035);\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("  }\r\n");
      out.write(".submitButton:disabled,\r\n");
      out.write("button[disabled] {\r\n");
      out.write("  border: 1px solid #cccccc;\r\n");
      out.write("  background-color: #cccccc;\r\n");
      out.write("  color: #666666;\r\n");
      out.write("}\r\n");
      out.write("h6.error {\r\n");
      out.write("    color: red;\r\n");
      out.write("}\r\n");
      out.write("#loader {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  margin: -2px 0 0 10px;\r\n");
      out.write("  border: 4px solid #f3f3f3;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  border-top: 4px solid #666666;\r\n");
      out.write("  width: 14px;\r\n");
      out.write("  height: 14px;\r\n");
      out.write("  -webkit-animation: spin 2s linear infinite;\r\n");
      out.write("  animation: spin 2s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes spin {\r\n");
      out.write("    0% { transform: rotate(0deg); }\r\n");
      out.write("    100% { transform: rotate(360deg); }\r\n");
      out.write("}\r\n");
      out.write(".inputLabel{\r\n");
      out.write("  text-align: initial;\r\n");
      out.write("}\r\n");
      out.write(".navbar .navbar-menu-wrapper .search-field .input-group input {\r\n");
      out.write("    font-size: 1.5rem;\r\n");
      out.write("    padding: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("  <body>\r\n");
      out.write("   ");
User user = (User)request.getAttribute("user"); 
      out.write("\r\n");
      out.write("    ");
ArrayList<Group> glist = (ArrayList<Group>)request.getAttribute("glist"); 
      out.write(" \r\n");
      out.write("    <div class=\"container-scroller\">\r\n");
      out.write("      <div class=\"row p-0 m-0 proBanner\" id=\"proBanner\">\r\n");
      out.write("        <div class=\"col-md-12 p-0 m-0\">\r\n");
      out.write("          <div class=\"card-body card-body-padding d-flex align-items-center justify-content-between\">\r\n");
      out.write("            <div class=\"ps-lg-1\">\r\n");
      out.write("              <div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("                <p class=\"mb-0 font-weight-medium me-3 buy-now-text\">Free 24/7 customer support, updates, and more with this template!</p>\r\n");
      out.write("                <a href=\"https://www.bootstrapdash.com/product/purple-bootstrap-admin-template/?utm_source=organic&utm_medium=banner&utm_campaign=buynow_demo\" target=\"_blank\" class=\"btn me-2 buy-now-btn border-0\">Get Pro</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("              <a href=\"https://www.bootstrapdash.com/product/purple-bootstrap-admin-template/\"><i class=\"mdi mdi-home me-3 text-white\"></i></a>\r\n");
      out.write("              <button id=\"bannerClose\" class=\"btn border-0 p-0\">\r\n");
      out.write("                <i class=\"mdi mdi-close text-white me-0\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- partial:partials/_navbar.html -->\r\n");
      out.write("      <nav class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("        <div class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("          <a class=\"navbar-brand brand-logo\" href=\"#\"><img src=\"assets/images/logo2.png\" alt=\"logo\" aspect-ratio=167/419 style=\"height:66px;width:172px;\"></a>\r\n");
      out.write("          <a class=\"navbar-brand brand-logo-mini\" href=\"#\"><img src=\"assets/images/logo-mini.svg\" alt=\"logo\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("          <button class=\"navbar-toggler navbar-toggler align-self-center\" type=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("            <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <div class=\"search-field d-none d-md-block\">\r\n");
      out.write("            <form class=\"d-flex align-items-center h-100\" action=\"#\">\r\n");
      out.write("              <div class=\"input-group\">\r\n");
      out.write("                <div class=\"input-group-prepend bg-transparent\">\r\n");
      out.write("                  <i class=\"input-group-text border-0 mdi mdi-magnify\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"text\" class=\"form-control bg-transparent border-0\" placeholder=\"Search projects\">\r\n");
      out.write("                </div><div>\r\n");
      out.write("                 ");
if(request.getAttribute("msg")!=null) {
      out.write("\r\n");
      out.write("			<h6 class=\"error\">");
      out.print(request.getAttribute("msg") );
      out.write("</h6>\r\n");
      out.write("										");
} 
      out.write("  \r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          <ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("            <li class=\"nav-item nav-profile dropdown\">\r\n");
      out.write("              <a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                <div class=\"nav-profile-img\">\r\n");
      out.write("                  <img src=\"assets/images/faces/face1.jpg\" alt=\"image\">\r\n");
      out.write("                  <span class=\"availability-status online\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-profile-text\">\r\n");
      out.write("                  <p class=\"mb-1 text-black\">");
      out.print(user.getuName() );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"dropdown-menu navbar-dropdown\" aria-labelledby=\"profileDropdown\">\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"./PhoneBookController?Action=GETUSER\" style=\"color: #2F2D3B;\">\r\n");
      out.write("                  <i class=\"fa fa-user-circle-o me-2\" style=\"color:rgb(88, 124, 241)\"></i>Profile</a>\r\n");
      out.write("                  <a class=\"dropdown-item\"  href=\"#myModal2\" data-toggle=\"modal\" style=\"color: #2F2D3B;\" >\r\n");
      out.write("                    <i class=\"fa fa-lock me-2\" style=\"color:rgb(96, 129, 236)\"></i> Password Change</a>\r\n");
      out.write("                    <a class=\"dropdown-item\"  href=\"./PhoneBookController?Action=USERDELETE\"  style=\"color: #2F2D3B;\" >\r\n");
      out.write("                    <i class=\"fa fa-lock me-2\" style=\"color:rgb(96, 129, 236)\"></i> Delete Account</a>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"./PhoneBookController?Action=LOGOUT\" style=\"color: #2F2D3B;\">\r\n");
      out.write("                  <i class=\"mdi mdi-logout me-2\" style=\"color:rgb(96, 129, 236)\"></i> Logout </a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("          \r\n");
      out.write("          </ul>\r\n");
      out.write("          <button class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\" type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("            <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <!-- partial -->\r\n");
      out.write("       \r\n");
      out.write("      <div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("        <!-- partial:partials/_sidebar.html -->\r\n");
      out.write("        <nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("          <ul class=\"nav\">\r\n");
      out.write("         \r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              \r\n");
      out.write("              <a class=\"nav-link\" href=\"./PhoneBookController?Action=DESBOARD1\">\r\n");
      out.write("                \r\n");
      out.write("                <span class=\"menu-title\"><i class=\"fa fa-dashboard\" style=\"font-size:20px;\"></i>&nbsp;Dashboard</span>\r\n");
      out.write("              \r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#ui-basic\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("                <span class=\"menu-title\"> <i class=\"fa fa-tablet\" style=\"font-size:20px\"></i>&nbsp;Application Registration</span>\r\n");
      out.write("                <i class=\"menu-arrow\"></i>\r\n");
      out.write("              \r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"collapse\" id=\"ui-basic\">\r\n");
      out.write("                <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=TOCREATCONTECT\">Create no</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=TOVIEWCONTECT\">View no</a></li> \r\n");
      out.write("                   <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=TOCREATEGROUP\">Create group</a></li> \r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("           \r\n");
      out.write("          <!--   <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" data-bs-toggle=\"collapse\"  href=\"./PhoneBookController?Action=TOCREATEGROUP\" aria-expanded=\"false\" aria-controls=\"ui-basic1\">\r\n");
      out.write("                <span class=\"menu-title\">  <i class=\"	fa fa-line-chart\" style=\"font-size:20px\"></i>&nbsp;MY GROUP</span>\r\n");
      out.write("                <i class=\"menu-arrow\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"collapse\" id=\"ui-basic1\">\r\n");
      out.write("                <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                 <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=TOCREATEGROUP\">Create group</a></li> -->\r\n");
      out.write("                  <!-- <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/plan.html\">Plan Selection</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/income.html\">Income Details</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/education.html\">Education Details</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/kids.html\">Kids Details</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/summary.html\">Summary Screen</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>  --> \r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#ui-basic2\" aria-expanded=\"false\" aria-controls=\"ui-basic2\">\r\n");
      out.write("                <span class=\"menu-title\"><i class=\"fa fa-th-large\" style=\"font-size:20px\"></i>&nbsp;View Group</span>\r\n");
      out.write("                <i class=\"menu-arrow\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"collapse\" id=\"ui-basic2\">\r\n");
      out.write("                <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                  ");
for(Group group:glist) 
                   {
                   
      out.write("\r\n");
      out.write("                   <li class =\"nav-item\"><a class=\"nav-link\" href=\"./PhoneBookController?Action=GETGROUP&gid=");
      out.print(group.getgId());
      out.write('"');
      out.write('>');
      out.print(group.getgName() );
      out.write("</a></li>\r\n");
      out.write("                   \r\n");
      out.write("                   ");
} 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("           \r\n");
      out.write("         ");
if(user.getuRole().equals("admin")) {
      out.write("\r\n");
      out.write("               \r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#general-pages\" aria-expanded=\"false\" aria-controls=\"general-pages\">\r\n");
      out.write("                <span class=\"menu-title\"><i class=\"fa fa-bars\" style=\"font-size:20px\"></i>&nbsp;Total User:-   ");
      out.print( request.getAttribute("count") );
      out.write("</span> </a></li>\r\n");
      out.write("                <!-- <i class=\"menu-arrow\"></i>\r\n");
      out.write("               -->\r\n");
      out.write("             <!--  </a> -->\r\n");
      out.write("             <!--  <div class=\"collapse\" id=\"general-pages\">\r\n");
      out.write("                <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/viewnotic.html\">Correspondence</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/viewnotic.html\">Pending Notices</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/viewnotic.html\">History Notices</a></li>\r\n");
      out.write("                 \r\n");
      out.write("                </ul>\r\n");
      out.write("              </div> -->\r\n");
      out.write("          <!--   </li> -->\r\n");
      out.write("            <!--\r\n");
      out.write("          \r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"pages/ui-features/insurance.html\">\r\n");
      out.write("                <span class=\"menu-title\">  <i class=\"fas fa-award\" style=\"font-size:20px\"></i> &nbsp;Benifit Issuance</span>\r\n");
      out.write("              \r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"pages/ui-features/reports.html\">\r\n");
      out.write("                <span class=\"menu-title\"> <i class=\"fa fa-edit\" style=\"font-size:20px\"></i>&nbsp;Reports</span>\r\n");
      out.write("              \r\n");
      out.write("              </a>\r\n");
      out.write("            </li> -->\r\n");
      out.write("             \r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#ui\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("                <span class=\"menu-title\"> <i class=\"fa fa-edit\" style=\"font-size:20px\"></i>&nbsp;Admin</span>\r\n");
      out.write("                <i class=\"menu-arrow\"></i>\r\n");
      out.write("              \r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"collapse\" id=\"ui\">\r\n");
      out.write("                <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=AUBYADMIN\">Create Account</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=TOVACCOUNTBYADMIN\">View Account</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("              ");
} 
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- partial -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"main-panel\">\r\n");
      out.write("          <div class=\"content-wrapper\">\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("              <h3 class=\"page-title\">\r\n");
      out.write("                <span class=\"page-title-icon bg-gradient-primary text-white me-2\">\r\n");
      out.write("                  <i class=\"mdi mdi-home\"></i>\r\n");
      out.write("                </span> Dashboard\r\n");
      out.write("              </h3>\r\n");
      out.write("              <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                <ul class=\"breadcrumb\">\r\n");
      out.write("                  <li class=\"breadcrumb-item active\" aria-current=\"page\">\r\n");
      out.write("                    <span></span>Overview <i class=\"mdi mdi-alert-circle-outline icon-sm text-primary align-middle\"></i>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-3 stretch-card grid-margin\">\r\n");
      out.write("                <div class=\"card bg-gradient-danger card-img-holder text-white\" style=\"border-radius: 10px;\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <img src=\"assets/images/dashboard/circle.svg\" class=\"card-img-absolute\" alt=\"circle-image\" />\r\n");
      out.write("                    <h4 class=\"font-weight-normal mb-3\">No. of Plans Available\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <h2 class=\"mb\">23</h2>\r\n");
      out.write("                    <h6 class=\"card-text\"> Jan-Oct 2021 <i class=\"fa fa-shopping-cart\" style=\"color:rgb(238, 234, 234);float: right;font-size:40px;\"></i></h6>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 stretch-card grid-margin\">\r\n");
      out.write("                <div class=\"card bg-gradient-info card-img-holder text-white\" style=\"border-radius: 10px;\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <img src=\"assets/images/dashboard/circle.svg\" class=\"card-img-absolute\" alt=\"circle-image\" />\r\n");
      out.write("                    <h4 class=\"font-weight-normal mb-3\">Citizens Approved\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <h2 class=\"mb\">8577641</h2>\r\n");
      out.write("                    <h6 class=\"card-text\">Jan-Oct 2021  <i class=\"	far fa-money-bill-alt\" style=\"color:rgb(238, 234, 234);float: right;font-size:40px;\"></i></h6>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 stretch-card grid-margin\">\r\n");
      out.write("                <div class=\"card bg-gradient-success card-img-holder text-white\" style=\"border-radius: 10px;\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <img src=\"assets/images/dashboard/circle.svg\" class=\"card-img-absolute\" alt=\"circle-image\" />\r\n");
      out.write("                    <h4 class=\"font-weight-normal mb-3\">Citizens Denied\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <h2 class=\"mb\">4565</h2>\r\n");
      out.write("                    <h6 class=\"card-text\">Jan-Oct 2021 <i class=\"fa fa-users\" style=\"color:rgb(238, 234, 234);float: right;font-size:40px;\"></i></h6>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 stretch-card grid-margin\">\r\n");
      out.write("                <div class=\"card bg-gradient-success card-img-holder text-white\" style=\"border-radius: 10px;\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <img src=\"assets/images/dashboard/circle.svg\" class=\"card-img-absolute\" alt=\"circle-image\" />\r\n");
      out.write("                    <h4 class=\"font-weight-normal mb-3\">Families Benefited \r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <h2 class=\"mb\">5676</h2>\r\n");
      out.write("                    <h6 class=\"card-text\">Jan-Oct 2021<i class=\"fa fa-heart\" style=\"color:rgb(238, 234, 234);float: right;font-size:40px;\"></i></h6>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-7 grid-margin stretch-card\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <div class=\"clearfix\">\r\n");
      out.write("                      <h4 class=\"card-title float-left\">Visit And Sales Statistics</h4>\r\n");
      out.write("                      <div id=\"visit-sale-chart-legend\" class=\"rounded-legend legend-horizontal legend-top-right float-right\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <canvas id=\"visit-sale-chart\" class=\"mt-4\"></canvas>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-5 grid-margin stretch-card\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <h4 class=\"card-title\">Traffic Sources</h4>\r\n");
      out.write("                    <canvas id=\"traffic-chart\"></canvas>\r\n");
      out.write("                    <div id=\"traffic-chart-legend\" class=\"rounded-legend legend-vertical legend-bottom-left pt-4\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-12 grid-margin\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <h4 class=\"card-title\">Recent Tickets</h4>\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                      <table class=\"table\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <th> Assignee </th>\r\n");
      out.write("                            <th> Subject </th>\r\n");
      out.write("                            <th> Status </th>\r\n");
      out.write("                            <th> Last Update </th>\r\n");
      out.write("                            <th> Tracking ID </th>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <img src=\"assets/images/faces/face1.jpg\" class=\"me-2\" alt=\"image\"> David Grey\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td> Fund is not recieved </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <label class=\"badge badge-gradient-success\">DONE</label>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td> Dec 5, 2017 </td>\r\n");
      out.write("                            <td> WD-12345 </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <img src=\"assets/images/faces/face2.jpg\" class=\"me-2\" alt=\"image\"> Stella Johnson\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td> High loading time </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <label class=\"badge badge-gradient-warning\">PROGRESS</label>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td> Dec 12, 2017 </td>\r\n");
      out.write("                            <td> WD-12346 </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <img src=\"assets/images/faces/face3.jpg\" class=\"me-2\" alt=\"image\"> Marina Michel\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td> Website down for one week </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <label class=\"badge badge-gradient-info\">ON HOLD</label>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td> Dec 16, 2017 </td>\r\n");
      out.write("                            <td> WD-12347 </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <img src=\"assets/images/faces/face4.jpg\" class=\"me-2\" alt=\"image\"> John Doe\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td> Loosing control on server </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <label class=\"badge badge-gradient-danger\">REJECTED</label>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td> Dec 3, 2017 </td>\r\n");
      out.write("                            <td> WD-12348 </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                      </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-12 grid-margin stretch-card\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <h4 class=\"card-title\">Recent Updates</h4>\r\n");
      out.write("                    <div class=\"d-flex\">\r\n");
      out.write("                      <div class=\"d-flex align-items-center me-4 text-muted font-weight-light\">\r\n");
      out.write("                        <i class=\"mdi mdi-account-outline icon-sm me-2\"></i>\r\n");
      out.write("                        <span>jack Menqu</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"d-flex align-items-center text-muted font-weight-light\">\r\n");
      out.write("                        <i class=\"mdi mdi-clock icon-sm me-2\"></i>\r\n");
      out.write("                        <span>October 3rd, 2018</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row mt-3\">\r\n");
      out.write("                      <div class=\"col-6 pe-1\">\r\n");
      out.write("                        <img src=\"assets/images/dashboard/img_1.jpg\" class=\"mb-2 mw-100 w-100 rounded\" alt=\"image\">\r\n");
      out.write("                        <img src=\"assets/images/dashboard/img_4.jpg\" class=\"mw-100 w-100 rounded\" alt=\"image\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-6 ps-1\">\r\n");
      out.write("                        <img src=\"assets/images/dashboard/img_2.jpg\" class=\"mb-2 mw-100 w-100 rounded\" alt=\"image\">\r\n");
      out.write("                        <img src=\"assets/images/dashboard/img_3.jpg\" class=\"mw-100 w-100 rounded\" alt=\"image\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex mt-5 align-items-top\">\r\n");
      out.write("                      <img src=\"assets/images/faces/face3.jpg\" class=\"img-sm rounded-circle me-3\" alt=\"image\">\r\n");
      out.write("                      <div class=\"mb-0 flex-grow\">\r\n");
      out.write("                        <h5 class=\"me-2 mb-2\">School Website - Authentication Module.</h5>\r\n");
      out.write("                        <p class=\"mb-0 font-weight-light\">It is a long established fact that a reader will be distracted by the readable content of a page.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"ms-auto\">\r\n");
      out.write("                        <i class=\"mdi mdi-heart-outline text-muted\"></i>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-7 grid-margin stretch-card\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <h4 class=\"card-title\">Project Status</h4>\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                      <table class=\"table\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <th> # </th>\r\n");
      out.write("                            <th> Name </th>\r\n");
      out.write("                            <th> Due Date </th>\r\n");
      out.write("                            <th> Progress </th>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td> 1 </td>\r\n");
      out.write("                            <td> Herman Beck </td>\r\n");
      out.write("                            <td> May 15, 2015 </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <div class=\"progress\">\r\n");
      out.write("                                <div class=\"progress-bar bg-gradient-success\" role=\"progressbar\" style=\"width: 25%\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td> 2 </td>\r\n");
      out.write("                            <td> Messsy Adam </td>\r\n");
      out.write("                            <td> Jul 01, 2015 </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <div class=\"progress\">\r\n");
      out.write("                                <div class=\"progress-bar bg-gradient-danger\" role=\"progressbar\" style=\"width: 75%\" aria-valuenow=\"75\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td> 3 </td>\r\n");
      out.write("                            <td> John Richards </td>\r\n");
      out.write("                            <td> Apr 12, 2015 </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <div class=\"progress\">\r\n");
      out.write("                                <div class=\"progress-bar bg-gradient-warning\" role=\"progressbar\" style=\"width: 90%\" aria-valuenow=\"90\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td> 4 </td>\r\n");
      out.write("                            <td> Peter Meggik </td>\r\n");
      out.write("                            <td> May 15, 2015 </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <div class=\"progress\">\r\n");
      out.write("                                <div class=\"progress-bar bg-gradient-primary\" role=\"progressbar\" style=\"width: 50%\" aria-valuenow=\"50\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td> 5 </td>\r\n");
      out.write("                            <td> Edward </td>\r\n");
      out.write("                            <td> May 03, 2015 </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <div class=\"progress\">\r\n");
      out.write("                                <div class=\"progress-bar bg-gradient-danger\" role=\"progressbar\" style=\"width: 35%\" aria-valuenow=\"35\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td> 5 </td>\r\n");
      out.write("                            <td> Ronald </td>\r\n");
      out.write("                            <td> Jun 05, 2015 </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <div class=\"progress\">\r\n");
      out.write("                                <div class=\"progress-bar bg-gradient-info\" role=\"progressbar\" style=\"width: 65%\" aria-valuenow=\"65\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                      </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-5 grid-margin stretch-card\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <h4 class=\"card-title text-white\">Todo</h4>\r\n");
      out.write("                    <div class=\"add-items d-flex\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control todo-list-input\" placeholder=\"What do you need to do today?\">\r\n");
      out.write("                      <button class=\"add btn btn-gradient-primary font-weight-bold todo-list-add-btn\" id=\"add-task\">Add</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"list-wrapper\">\r\n");
      out.write("                      <ul class=\"d-flex flex-column-reverse todo-list todo-list-custom\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"checkbox\" type=\"checkbox\"> Meeting with Alisa </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <i class=\"remove mdi mdi-close-circle-outline\"></i>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"completed\">\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"checkbox\" type=\"checkbox\" checked> Call John </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <i class=\"remove mdi mdi-close-circle-outline\"></i>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"checkbox\" type=\"checkbox\"> Create invoice </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <i class=\"remove mdi mdi-close-circle-outline\"></i>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"checkbox\" type=\"checkbox\"> Print Statements </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <i class=\"remove mdi mdi-close-circle-outline\"></i>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"completed\">\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"checkbox\" type=\"checkbox\" checked> Prepare for presentation </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <i class=\"remove mdi mdi-close-circle-outline\"></i>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"checkbox\" type=\"checkbox\"> Pick up kids from school </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <i class=\"remove mdi mdi-close-circle-outline\"></i>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("              <!-- password change -->\r\n");
      out.write("              <div id=\"myModal2\" class=\"modal fade\">\r\n");
      out.write("                <div class=\"modal-dialog modal-confirm\">\r\n");
      out.write("                  <div class=\"modal-content\">\r\n");
      out.write("              \r\n");
      out.write("                                  \r\n");
      out.write("                      <div class=\"mainDiv\">\r\n");
      out.write("                        <div class=\"cardStyle\">\r\n");
      out.write("                          <form action=\"./PhoneBookController\" method=\"post\" name=\"signupForm\" id=\"signupForm\">\r\n");
      out.write("                            \r\n");
      out.write("                            <img src=\"\" id=\"signupLogo\"/>\r\n");
      out.write("                            \r\n");
      out.write("                            <h4 class=\"formTitle\">\r\n");
      out.write("                              Login to your account\r\n");
      out.write("                            </h4>\r\n");
      out.write("                            <div class=\"inputDiv\">\r\n");
      out.write("                              <label class=\"inputLabel\" for=\"password\">Current Password</label>\r\n");
      out.write("                              <input type=\"password\" id=\"password\" name=\"oldpassword\" required>\r\n");
      out.write("                              ");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                              \r\n");
      out.write("                          <div class=\"inputDiv\">\r\n");
      out.write("                            <label class=\"inputLabel\" for=\"password\">New Password</label>\r\n");
      out.write("                            <input type=\"password\" id=\"password\" name=\"newpassword\" required>\r\n");
      out.write("                          </div>\r\n");
      out.write("                            \r\n");
      out.write("                          <div class=\"inputDiv\">\r\n");
      out.write("                            <label class=\"inputLabel\" for=\"confirmPassword\">Confirm New Password</label>\r\n");
      out.write("                            <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                                    <input type=\"hidden\" id=\"confirmPassword\" name=\"Action\" value=\"CHANGEPASSWORD\">\r\n");
      out.write("                          <!-- <div>\r\n");
      out.write("                             <button type=\"submit\"  class=\"btn btn-primary\"  >Continue</button> \r\n");
      out.write(" -->                           ");
      out.write("\r\n");
      out.write("                              <!-- <span>Continue</span>\r\n");
      out.write("                              <span id=\"loader\"></span> -->\r\n");
      out.write("                              <!-- <button class=\"btn btn-primary\"  href=\"./PhoneBookController\"></button>\r\n");
      out.write("                               -->\r\n");
      out.write("                               <div class=\"buttonWrapper\">\r\n");
      out.write("                        <button type=\"submit\" id=\"submitButton\" onclick=\"validateSignupForm()\" class=\"submitButton pure-button pure-button-primary\">\r\n");
      out.write("                          <span>Continue</span>\r\n");
      out.write("                          \r\n");
      out.write("                        </button>\r\n");
      out.write("                              \r\n");
      out.write("                              \r\n");
      out.write("                         \r\n");
      out.write("                          </div>\r\n");
      out.write("                            \r\n");
      out.write("                        </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div> \r\n");
      out.write("              </div>\r\n");
      out.write("          <!-- content-wrapper ends -->\r\n");
      out.write("          <!-- partial:partials/_footer.html -->\r\n");
      out.write("          \r\n");
      out.write("          <!-- partial -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- main-panel ends -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- page-body-wrapper ends -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- container-scroller -->\r\n");
      out.write("    <!-- plugins:js -->\r\n");
      out.write("    <script src=\"assets/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("    <!-- endinject -->\r\n");
      out.write("    <!-- Plugin js for this page -->\r\n");
      out.write("    <script src=\"assets/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/jquery.cookie.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- End plugin js for this page -->\r\n");
      out.write("    <!-- inject:js -->\r\n");
      out.write("    <script src=\"assets/js/off-canvas.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/hoverable-collapse.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/misc.js\"></script>\r\n");
      out.write("    <!-- endinject -->\r\n");
      out.write("    <!-- Custom js for this page -->\r\n");
      out.write("    <script src=\"assets/js/dashboard.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/todolist.js\"></script>\r\n");
      out.write("    <!-- End custom js for this page -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
