/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-05-29 08:14:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.adda.app.Bean.User;
import com.adda.app.Bean.Contect;
import java.util.*;
import com.adda.app.Bean.Group;

public final class viewUserContectByAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.adda.app.Bean.Group");
    _jspx_imports_classes.add("com.adda.app.Bean.Contect");
    _jspx_imports_classes.add("com.adda.app.Bean.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>Contect View</title>\r\n");
      out.write("    <!-- plugins:css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("    <!-- endinject -->\r\n");
      out.write("    <!-- Plugin css for this page -->\r\n");
      out.write("    <!-- End Plugin css for this page -->\r\n");
      out.write("    <!-- inject:css -->\r\n");
      out.write("    <!-- endinject -->\r\n");
      out.write("    <!-- Layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/style.css\">\r\n");
      out.write("    <!-- End layout styles -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./assets/images/favicon.ico\" />\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/images/favicon.ico\" />\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css\">\r\n");
      out.write("     <!-- modal -->\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto|Varela+Round\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("     <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("     <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\r\n");
      out.write("     <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("<style>\r\n");
      out.write("  .dataTables_wrapper .dataTables_filter input {\r\n");
      out.write("    border: 1px solid #aaa;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    margin-left: 3px;\r\n");
      out.write("}\r\n");
      out.write(".dataTables_wrapper .dataTables_filter input {\r\n");
      out.write("    border: 1px solid #aaa;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    /* padding: 0px; */\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    margin-left: 3px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("/* password change */\r\n");
      out.write(".mainDiv {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("    font-family: 'Open Sans', sans-serif;\r\n");
      out.write("  }\r\n");
      out.write(" .cardStyle {\r\n");
      out.write("  width: 381px;\r\n");
      out.write("    border-color: white;\r\n");
      out.write("    /* background: #fff; */\r\n");
      out.write("    /* padding: 36px 0; */\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    margin: 30px 0;\r\n");
      out.write("    box-shadow: 0px 0 2px 0 rgba(0,0,0,0.25);\r\n");
      out.write("  }\r\n");
      out.write("#signupLogo {\r\n");
      out.write("  max-height: 100px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write(".formTitle{\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  color: #2F2D3B;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".inputLabel {\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  color: #555;\r\n");
      out.write("  margin-bottom: 6px;\r\n");
      out.write("  margin-top: 24px;\r\n");
      out.write("}\r\n");
      out.write("  .inputDiv {\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("  }\r\n");
      out.write("input {\r\n");
      out.write("  height: 40px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border: solid 1px #ccc;\r\n");
      out.write("  padding: 0 11px;\r\n");
      out.write("}\r\n");
      out.write("input:disabled {\r\n");
      out.write("  cursor: not-allowed;\r\n");
      out.write("  border: solid 1px #eee;\r\n");
      out.write("}\r\n");
      out.write(".buttonWrapper {\r\n");
      out.write("  margin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("  .submitButton {\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #065492;\r\n");
      out.write("    border-color: #065492;\r\n");
      out.write("    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("    box-shadow: 0 2px 0 rgba(0, 0, 0, 0.035);\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("  }\r\n");
      out.write(".submitButton:disabled,\r\n");
      out.write("button[disabled] {\r\n");
      out.write("  border: 1px solid #cccccc;\r\n");
      out.write("  background-color: #cccccc;\r\n");
      out.write("  color: #666666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loader {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  margin: -2px 0 0 10px;\r\n");
      out.write("  border: 4px solid #f3f3f3;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  border-top: 4px solid #666666;\r\n");
      out.write("  width: 14px;\r\n");
      out.write("  height: 14px;\r\n");
      out.write("  -webkit-animation: spin 2s linear infinite;\r\n");
      out.write("  animation: spin 2s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("img {\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border-style: none;\r\n");
      out.write("    height: 51px;\r\n");
      out.write("}\r\n");
      out.write("@keyframes spin {\r\n");
      out.write("    0% { transform: rotate(0deg); }\r\n");
      out.write("    100% { transform: rotate(360deg); }\r\n");
      out.write("}\r\n");
      out.write(".inputLabel{\r\n");
      out.write("  text-align: initial;\r\n");
      out.write("}\r\n");
      out.write(".navbar .navbar-menu-wrapper .search-field .input-group input {\r\n");
      out.write("    font-size: 1.5rem;\r\n");
      out.write("    padding: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("  <body>\r\n");
      out.write("  ");
User user = (User)request.getAttribute("user"); 
      out.write("\r\n");
      out.write("  ");
List<Contect> list=(ArrayList)request.getAttribute("conlist");
		
      out.write('\r');
      out.write('\n');
      out.write('	');
List<Group>glist=(ArrayList)request.getAttribute("glist"); 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("    <div class=\"container-scroller\">\r\n");
      out.write("      <!-- partial:../../partials/_navbar.html -->\r\n");
      out.write("      <nav class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("        <div class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("          <a class=\"navbar-brand brand-logo\" href=\"#\"><img src=\"./assets/images/logo2.png\" alt=\"logo\" aspect-ratio=167/419 style=\"height:66px;width:172px;\"></a>\r\n");
      out.write("          <a class=\"navbar-brand brand-logo-mini\" href=\"#\"><img src=\"./assets/images/logo-mini.svg\" alt=\"logo\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("          <button class=\"navbar-toggler navbar-toggler align-self-center\" type=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("            <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <div class=\"search-field d-none d-md-block\">\r\n");
      out.write("            <form class=\"d-flex align-items-center h-100\" action=\"#\">\r\n");
      out.write("              <div class=\"input-group\">\r\n");
      out.write("                <div class=\"input-group-prepend bg-transparent\">\r\n");
      out.write("                  <i class=\"input-group-text border-0 mdi mdi-magnify\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"text\" class=\"form-control bg-transparent border-0\" placeholder=\"Search projects\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          <ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("            <li class=\"nav-item nav-profile dropdown\">\r\n");
      out.write("              <a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                <div class=\"nav-profile-img\">\r\n");
      out.write("                  <img src=\"./assets/images/faces/face1.jpg\" alt=\"image\">\r\n");
      out.write("                  <span class=\"availability-status online\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-profile-text\">\r\n");
      out.write("                  <p class=\"mb-1 text-black\">");
      out.print(user.getuName() );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"dropdown-menu navbar-dropdown\" aria-labelledby=\"profileDropdown\">\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"./PhoneBookController?Action=GETUSER\" style=\"color: #2F2D3B;\">\r\n");
      out.write("                  <i class=\"fa fa-user-circle-o me-2\" style=\"color:rgb(88, 124, 241)\"></i>Profile</a>\r\n");
      out.write("                  <a class=\"dropdown-item\"  href=\"#myModal2\"  data-toggle=\"modal\" style=\"color: #2F2D3B;\">\r\n");
      out.write("                    <i class=\"fa fa-lock me-2\" style=\"color:rgb(96, 129, 236)\"></i> Password Change</a>\r\n");
      out.write("                    <a class=\"dropdown-item\"  href=\"./PhoneBookController?Action=USERDELETE\"  style=\"color: #2F2D3B;\" >\r\n");
      out.write("                    <i class=\"fa fa-lock me-2\" style=\"color:rgb(96, 129, 236)\"></i> Delete Account</a>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"./PhoneBookController?Action=LOGOUT\" style=\"color: #2F2D3B;\">\r\n");
      out.write("                  <i class=\"mdi mdi-logout me-2\" style=\"color:rgb(96, 129, 236)\"></i> Logout </a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <!-- <li class=\"nav-item d-none d-lg-block full-screen-link\">\r\n");
      out.write("              <a class=\"nav-link\">\r\n");
      out.write("                <i class=\"mdi mdi-fullscreen\" id=\"fullscreen-button\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("              <a class=\"nav-link count-indicator dropdown-toggle\" id=\"messageDropdown\" href=\"#\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                <i class=\"mdi mdi-email-outline\"></i>\r\n");
      out.write("                <span class=\"count-symbol bg-warning\"></span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list\" aria-labelledby=\"messageDropdown\">\r\n");
      out.write("                <h6 class=\"p-3 mb-0\">Messages</h6>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <a class=\"dropdown-item preview-item\">\r\n");
      out.write("                  <div class=\"preview-thumbnail\">\r\n");
      out.write("                    <img src=\"./assets/images/faces/face4.jpg\" alt=\"image\" class=\"profile-pic\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("                    <h6 class=\"preview-subject ellipsis mb-1 font-weight-normal\">Mark send you a message</h6>\r\n");
      out.write("                    <p class=\"text-gray mb-0\"> 1 Minutes ago </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <a class=\"dropdown-item preview-item\">\r\n");
      out.write("                  <div class=\"preview-thumbnail\">\r\n");
      out.write("                    <img src=\"./assets/images/faces/face2.jpg\" alt=\"image\" class=\"profile-pic\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("                    <h6 class=\"preview-subject ellipsis mb-1 font-weight-normal\">Cregh send you a message</h6>\r\n");
      out.write("                    <p class=\"text-gray mb-0\"> 15 Minutes ago </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <a class=\"dropdown-item preview-item\">\r\n");
      out.write("                  <div class=\"preview-thumbnail\">\r\n");
      out.write("                    <img src=\"./assets/images/faces/face3.jpg\" alt=\"image\" class=\"profile-pic\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("                    <h6 class=\"preview-subject ellipsis mb-1 font-weight-normal\">Profile picture updated</h6>\r\n");
      out.write("                    <p class=\"text-gray mb-0\"> 18 Minutes ago </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <h6 class=\"p-3 mb-0 text-center\">4 new messages</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("              <a class=\"nav-link count-indicator dropdown-toggle\" id=\"notificationDropdown\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                <i class=\"mdi mdi-bell-outline\"></i>\r\n");
      out.write("                <span class=\"count-symbol bg-danger\"></span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list\" aria-labelledby=\"notificationDropdown\">\r\n");
      out.write("                <h6 class=\"p-3 mb-0\">Notifications</h6>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <a class=\"dropdown-item preview-item\">\r\n");
      out.write("                  <div class=\"preview-thumbnail\">\r\n");
      out.write("                    <div class=\"preview-icon bg-success\">\r\n");
      out.write("                      <i class=\"mdi mdi-calendar\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("                    <h6 class=\"preview-subject font-weight-normal mb-1\">Event today</h6>\r\n");
      out.write("                    <p class=\"text-gray ellipsis mb-0\"> Just a reminder that you have an event today </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <a class=\"dropdown-item preview-item\">\r\n");
      out.write("                  <div class=\"preview-thumbnail\">\r\n");
      out.write("                    <div class=\"preview-icon bg-warning\">\r\n");
      out.write("                      <i class=\"mdi mdi-settings\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("                    <h6 class=\"preview-subject font-weight-normal mb-1\">Settings</h6>\r\n");
      out.write("                    <p class=\"text-gray ellipsis mb-0\"> Update dashboard </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <a class=\"dropdown-item preview-item\">\r\n");
      out.write("                  <div class=\"preview-thumbnail\">\r\n");
      out.write("                    <div class=\"preview-icon bg-info\">\r\n");
      out.write("                      <i class=\"mdi mdi-link-variant\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("                    <h6 class=\"preview-subject font-weight-normal mb-1\">Launch Admin</h6>\r\n");
      out.write("                    <p class=\"text-gray ellipsis mb-0\"> New admin wow! </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <h6 class=\"p-3 mb-0 text-center\">See all notifications</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item nav-logout d-none d-lg-block\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("                <i class=\"mdi mdi-power\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item nav-settings d-none d-lg-block\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("                <i class=\"mdi mdi-format-line-spacing\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li> -->\r\n");
      out.write("          </ul>\r\n");
      out.write("          <button class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\" type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("            <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <!-- partial -->\r\n");
      out.write("       <div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("        <!-- partial:partials/_sidebar.html -->\r\n");
      out.write("        <nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("          <ul class=\"nav\">\r\n");
      out.write("         \r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              \r\n");
      out.write("              <a class=\"nav-link\" href=\"./PhoneBookController?Action=DESBOARD1\">\r\n");
      out.write("                \r\n");
      out.write("                <span class=\"menu-title\"><i class=\"fa fa-dashboard\" style=\"font-size:20px;\"></i>&nbsp;Dashboard</span>\r\n");
      out.write("              \r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#ui-basic\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("                <span class=\"menu-title\"> <i class=\"fa fa-tablet\" style=\"font-size:20px\"></i>&nbsp;Application Registration</span>\r\n");
      out.write("                <i class=\"menu-arrow\"></i>\r\n");
      out.write("              \r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"collapse\" id=\"ui-basic\">\r\n");
      out.write("                <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=TOCREATCONTECT\">Create no</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=TOVIEWCONTECT\">View no</a></li> \r\n");
      out.write("                   <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=TOCREATEGROUP\">Create group</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("           <!--  <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#ui-basic1\" aria-expanded=\"false\" aria-controls=\"ui-basic1\">\r\n");
      out.write("                <span class=\"menu-title\">  <i class=\"	fa fa-line-chart\" style=\"font-size:20px\"></i>&nbsp;MY GROUP</span>\r\n");
      out.write("                <i class=\"menu-arrow\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"collapse\" id=\"ui-basic1\"> -->\r\n");
      out.write("                <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("              <!--     <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=TOCREATEGROUP\">Create group</a></li> -->\r\n");
      out.write("                  <!-- <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/plan.html\">Plan Selection</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/income.html\">Income Details</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/education.html\">Education Details</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/kids.html\">Kids Details</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/summary.html\">Summary Screen</a></li> -->\r\n");
      out.write("               <!--  </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li> -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#ui-basic2\" aria-expanded=\"false\" aria-controls=\"ui-basic2\">\r\n");
      out.write("                <span class=\"menu-title\"><i class=\"fa fa-th-large\" style=\"font-size:20px\"></i>&nbsp;View Group</span>\r\n");
      out.write("                <i class=\"menu-arrow\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"collapse\" id=\"ui-basic2\">\r\n");
      out.write("                <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                  ");
for(Group group:glist) 
                   {
                   
      out.write("\r\n");
      out.write("                   <li class =\"nav-item\"><a class=\"nav-link\" href=\"./PhoneBookController?Action=GETGROUP&gid=");
      out.print(group.getgId());
      out.write('"');
      out.write('>');
      out.print(group.getgName() );
      out.write("</a></li>\r\n");
      out.write("                   \r\n");
      out.write("                   ");
} 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("           \r\n");
      out.write("         ");
if(user.getuRole().equals("admin")) {
      out.write("\r\n");
      out.write("               \r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#general-pages\" aria-expanded=\"false\" aria-controls=\"general-pages\">\r\n");
      out.write("                <span class=\"menu-title\"><i class=\"fa fa-bars\" style=\"font-size:20px\"></i>&nbsp;Total User:-   ");
      out.print( request.getAttribute("count") );
      out.write("</span> </a></li>\r\n");
      out.write("                <!-- <i class=\"menu-arrow\"></i>\r\n");
      out.write("               -->\r\n");
      out.write("             <!--  </a> -->\r\n");
      out.write("             <!--  <div class=\"collapse\" id=\"general-pages\">\r\n");
      out.write("                <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/viewnotic.html\">Correspondence</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/viewnotic.html\">Pending Notices</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/viewnotic.html\">History Notices</a></li>\r\n");
      out.write("                 \r\n");
      out.write("                </ul>\r\n");
      out.write("              </div> -->\r\n");
      out.write("          <!--   </li> -->\r\n");
      out.write("            <!--\r\n");
      out.write("          \r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"pages/ui-features/insurance.html\">\r\n");
      out.write("                <span class=\"menu-title\">  <i class=\"fas fa-award\" style=\"font-size:20px\"></i> &nbsp;Benifit Issuance</span>\r\n");
      out.write("              \r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"pages/ui-features/reports.html\">\r\n");
      out.write("                <span class=\"menu-title\"> <i class=\"fa fa-edit\" style=\"font-size:20px\"></i>&nbsp;Reports</span>\r\n");
      out.write("              \r\n");
      out.write("              </a>\r\n");
      out.write("            </li> -->\r\n");
      out.write("             \r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#ui\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("                <span class=\"menu-title\"> <i class=\"fa fa-edit\" style=\"font-size:20px\"></i>&nbsp;Admin</span>\r\n");
      out.write("                <i class=\"menu-arrow\"></i>\r\n");
      out.write("              \r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"collapse\" id=\"ui\">\r\n");
      out.write("                <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=AUBYADMIN\">Create Account</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"> <a class=\"nav-link\" href=\"./PhoneBookController?Action=TOVACCOUNTBYADMIN\">View Account</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("              ");
} 
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- partial -->\r\n");
      out.write("        <div class=\"main-panel\">\r\n");
      out.write("          <div class=\"content-wrapper\">\r\n");
      out.write("            <!-- <div class=\"page-header\">\r\n");
      out.write("              <h3 class=\"page-title\"> Buttons </h3>\r\n");
      out.write("              <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                <ol class=\"breadcrumb\">\r\n");
      out.write("                  <li class=\"breadcrumb-item\"><a href=\"#\">UI Elements</a></li>\r\n");
      out.write("                  <li class=\"breadcrumb-item active\" aria-current=\"page\">Buttons</li>\r\n");
      out.write("                </ol>\r\n");
      out.write("              </nav>\r\n");
      out.write("            </div> -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-12 grid-margin stretch-card\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <h4 class=\"card-title\">View Applicatins</h4>\r\n");
      out.write("                 </div>\r\n");
      out.write("               </div>\r\n");
      out.write("              </div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("    \r\n");
      out.write("              <!-- <div class=\"col-12 grid-margin stretch-card\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <form action=\"/action_page.php\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"number\">Case Number</label>\r\n");
      out.write("                        <input type=\"\" class=\"form-control\" placeholder=\"123456\" id=\"number\" style=\"background-color:rgb(244, 244, 245);\">\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-default\" style=\"background-color: rgb(118, 118, 240);color: #fff;border-radius:5px;\">Search</button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    \r\n");
      out.write("                     \r\n");
      out.write("                    </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div> -->\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-12 grid-margin stretch-card\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <div style=\"overflow-x:auto;\">\r\n");
      out.write("                    <table id=\"example\" class=\"display hover\" style=\"width:100%;height:220px;\">\r\n");
      out.write("                      <thead>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                              \r\n");
      out.write("                              <th> Name</th>\r\n");
      out.write("                              <th>Email ID</th>\r\n");
      out.write("                              <th>Mobile Number</th>\r\n");
      out.write("                              <th>Address</th>\r\n");
      out.write("                              <!-- <th>Favorite Contect</th>\r\n");
      out.write("                              <th>Action</th> -->\r\n");
      out.write("                             <!--  <th>DOB</th>\r\n");
      out.write("                              <th>SSN</th> -->\r\n");
      out.write("                              \r\n");
      out.write("                          </tr>\r\n");
      out.write("                      </thead><br>\r\n");
      out.write("                      <tbody id=\"showData\">\r\n");
      out.write("                          ");
 
                          for(Contect l:list){ 
      out.write("\r\n");
      out.write("                          <tr>\r\n");
      out.write("                          <td>");
      out.print(l.getcName() );
      out.write("</td>\r\n");
      out.write("                          <td>");
      out.print(l.getcEmail() );
      out.write("</td>\r\n");
      out.write("                          <td>");
      out.print(l.getcMobile() );
      out.write("</td>\r\n");
      out.write("                          <td>");
      out.print(l.getcAddress() );
      out.write("</td>\r\n");
      out.write("                          ");
      out.write("\r\n");
      out.write("                         ");
      out.write("\r\n");
      out.write("                         \r\n");
      out.write("                          </tr>\r\n");
      out.write("                          ");

                          }
      out.write("\r\n");
      out.write("                      </tbody>\r\n");
      out.write("                  </table><br><br>\r\n");
      out.write("                  </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("               </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("           <!-- password change -->\r\n");
      out.write("           <div id=\"myModal2\" class=\"modal fade\">\r\n");
      out.write("            <div class=\"modal-dialog modal-confirm\">\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("          \r\n");
      out.write("                              \r\n");
      out.write("                  <div class=\"mainDiv\">\r\n");
      out.write("                    <div class=\"cardStyle\">\r\n");
      out.write("                      <form action=\"./PhoneBookController?Action=CHANGEPASSWORD\" method=\"post\" name=\"signupForm\" id=\"signupForm\">\r\n");
      out.write("                        \r\n");
      out.write("                        <img src=\"\" id=\"signupLogo\"/>\r\n");
      out.write("                        \r\n");
      out.write("                        <h4 class=\"formTitle\">\r\n");
      out.write("                          Login to your account\r\n");
      out.write("                        </h4>\r\n");
      out.write("                        <div class=\"inputDiv\">\r\n");
      out.write("                          <label class=\"inputLabel\" for=\"password\">Current Password</label>\r\n");
      out.write("                          <input type=\"password\" id=\"password\" name=\"oldpassword\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                          \r\n");
      out.write("                      <div class=\"inputDiv\">\r\n");
      out.write("                        <label class=\"inputLabel\" for=\"password\">New Password</label>\r\n");
      out.write("                        <input type=\"password\" id=\"password\" name=\"newpassword\" required>\r\n");
      out.write("                      </div>\r\n");
      out.write("                        \r\n");
      out.write("                      <div class=\"inputDiv\">\r\n");
      out.write("                        <label class=\"inputLabel\" for=\"confirmPassword\">Confirm New Password</label>\r\n");
      out.write("                        <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"buttonWrapper\">\r\n");
      out.write("                        <button type=\"submit\" id=\"submitButton\" onclick=\"validateSignupForm()\" class=\"submitButton pure-button pure-button-primary\">\r\n");
      out.write("                          <span>Continue</span>\r\n");
      out.write("                          \r\n");
      out.write("                        </button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div> \r\n");
      out.write("          </div> \r\n");
      out.write("          <!-- content-wrapper ends -->\r\n");
      out.write("          <!-- partial:../../partials/_footer.html -->\r\n");
      out.write("          \r\n");
      out.write("          <!-- partial -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- main-panel ends -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- page-body-wrapper ends -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- container-scroller -->\r\n");
      out.write("    <!-- plugins:js -->\r\n");
      out.write("    <script src=\"./assets/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("    <!-- endinject -->\r\n");
      out.write("    <!-- Plugin js for this page -->\r\n");
      out.write("    <!-- End plugin js for this page -->\r\n");
      out.write("    <!-- inject:js -->\r\n");
      out.write("    <script src=\"./assets/js/off-canvas.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/hoverable-collapse.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/misc.js\"></script>\r\n");
      out.write("              \r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    showData();\r\n");
      out.write("});\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("  $(document).ready(function() {\r\n");
      out.write("    $('#example').DataTable();\r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write("function showData(){\r\n");
      out.write("        var html = '';\r\n");
      out.write("      if ($.fn.DataTable.isDataTable('#example')){\r\n");
      out.write("         // destroy table\r\n");
      out.write("          $('#example').DataTable().destroy();\r\n");
      out.write("      }\r\n");
      out.write("        //  create tr td \r\n");
      out.write("        Object.keys(data).forEach(function(key) {\r\n");
      out.write("            html += '<tr>'; \r\n");
      out.write("            html += '<td>'+data[key].ID+'</td>';\r\n");
      out.write("            html += '<td>'+data[key].Name+'</td>'; \r\n");
      out.write("            html += '<td>'+data[key].Email+'</td>'; \r\n");
      out.write("            html += '<td>'+data[key].Mobile+'</td>'; \r\n");
      out.write("            html += '<td>'+data[key].Gender+'</td>';  \r\n");
      out.write("            html += '<td>'+data[key].Dob+'</td>';  \r\n");
      out.write("            html += '<td>'+data[key].Ssn+'</td>'; \r\n");
      out.write("           \r\n");
      out.write("            html += '</tr>';\r\n");
      out.write("        });\r\n");
      out.write("        $('#showData').html(html);\r\n");
      out.write("        // create table\r\n");
      out.write("        $(\"#example\").dataTable();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("/* var data = [\r\n");
      out.write("      {\r\n");
      out.write("            'ID':1, \r\n");
      out.write("            'Name' : 'johndoe',\r\n");
      out.write("            'Email' :'johndoe@gmail.com',\r\n");
      out.write("            'Mobile' : 1234567890,\r\n");
      out.write("            'Gender' : 'Male',\r\n");
      out.write("            'Dob' : '12/02/2000',\r\n");
      out.write("            'Ssn' : 1234567,\r\n");
      out.write("          \r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          'ID':2, \r\n");
      out.write("            'Name' : 'johndoe',\r\n");
      out.write("            'Email' :'johndoe@gmail.com',\r\n");
      out.write("            'Mobile' : 1234567890,\r\n");
      out.write("            'Gender' : 'Male',\r\n");
      out.write("            'Dob' : '12/02/2000',\r\n");
      out.write("            'Ssn' : 1234567,\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("          'ID':3, \r\n");
      out.write("            'Name' : 'johndoe',\r\n");
      out.write("            'Email' :'johndoe@gmail.com',\r\n");
      out.write("            'Mobile' : 1234567890,\r\n");
      out.write("            'Gender' : 'Male',\r\n");
      out.write("            'Dob' : '12/02/2000',\r\n");
      out.write("            'Ssn' : 1234567,\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write(" */\r\n");
      out.write("       \r\n");
      out.write("    ];\r\n");
      out.write("</script>\r\n");
      out.write("    <!-- endinject -->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
